CarHealth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('main/', include('main.urls'))
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns =  [path('index.html', views.main, name='main'),
                path('add_car', views.add_car, name='add_car'),
                path('update', views.update, name='update')]

main/models.py
from django.db import models
from login import models as login_models

# Create your models here.

class Car(models.Model):
    userId = models.ForeignKey(login_models.User, on_delete=models.CASCADE)
    manufacturer = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    kilometrage = models.IntegerField()
    year = models.IntegerField()
    checkDate = models.DateField()
    nextCheckDate = models.DateField()
    fuel = models.CharField(max_length=30, default="Dīzelis")
    engineVol = models.FloatField(default=1.5)
    def natural_key(self):
        return(self.manufacturer, self.model, self.year)

    def main_info(self):
        return {'kilometrage' : self.kilometrage,
                'manufactur date': self.year,
                'Last check date' : self.checkDate,
                'Next check date' :self.nextCheckDate,
                'Type of fuel' :self.fuel,
                'Engine volume' : self.engineVol}
    def get_car_parts(self):
        return Part.objects.filter(carId = self.pk)

class PartsType(models.Model):

    ConditionMeasurment = [
        ('KM', 'Kilometres'),
        ('MI', 'Miles'),
        ('Y', 'Year'),
        ('L', 'Volume')
    ]

    typeName = models.CharField(max_length=50)
    conditionMeasurment = models.CharField(max_length=5, choices=ConditionMeasurment, default='KM')
    stockCondition = models.FloatField()
    def natural_key(self):
        return (self.typeName, self.conditionMeasurment)



class Part(models.Model):
    carId = models.ForeignKey(Car, on_delete=models.CASCADE)
    serial = models.CharField(max_length=100,null=True)
    typeId = models.ForeignKey(PartsType, on_delete=models.CASCADE)
    manufacterDate = models.DateField(null=True)
    currentCondition = models.FloatField()
    additionalInfo = models.JSONField(null=True)

    def get_part_name(self):
        self.typeId.typeName

    def get_part_condition_measurment(self):
        PartsType.objects.get(self.typeId).values('conditionMeasurment')

main/forms.py
import re
from django import forms


class NewCarForm(forms.Form):
    manufacturer = forms.CharField(required=True)
    model = forms.CharField(required=True)
    engineType = forms.CharField(required=True)
    engineVol = forms.CharField(required=True)
    year = forms.IntegerField(required=True)
    widgets = forms.DateInput(
        format=('%Y-%m-%d'),
        attrs={'placeholder': '2020-01-01',
               'type': 'date',
               'value': '2020-01-01',
               'is_required': True
              }) 

    lastCheck = forms.DateField(widget= widgets, required=True)
    nextCheck = forms.DateField(required=True, widget= widgets )
    kilometrage = forms.IntegerField(required=True)

class UpdatePartForm(forms.Form):
    newValue = forms.FloatField()
    partId = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    carId = forms.IntegerField(widget=forms.HiddenInput())
    updateAll = forms.IntegerField(widget=forms.HiddenInput())

main/views.py
from django.shortcuts import render, redirect
from .models import *
from login.models import User
from .forms import *

# Create your views here.
def main(request):
    error = ''
    if 'user' in request.session:
        car_details = get_cars_details(request)
        context = {'error' : error} | car_details
        # forms = {}
        # for car in car_details.get('cars'):
        #     forms[car.pk] = UpdatePartForm(kilometrage = car.kilometrage, carId = car.pk)
        # context = context | {'forms': forms}
        context = context | {'update_form': UpdatePartForm()}
        context = context | {'new_car_form' : NewCarForm()}
    else:
        error = "You are not logged in"
        return render (request, "index.html", {'error' : error })
    return render (request, "index.html", context)

def add_car(request):
    error = ''
    form = NewCarForm(request.POST)
    if form.is_valid():
        if 'user' in request.session:
            logged_user = User.objects.get(pk = request.session['user'])
            fmanufacturer = form.cleaned_data.get('manufacturer')
            fmodel = form.cleaned_data.get('model')
            fengineType = form.cleaned_data.get('engineType')
            fengineVol = form.cleaned_data.get('engineVol')
            fyear = form.cleaned_data.get('year')
            flastCheck = form.cleaned_data.get('lastCheck')
            fnextCheck = form.cleaned_data.get('nextCheck')
            fkilometrage = form.cleaned_data.get('kilometrage')

            car = Car.objects.create(userId = logged_user,
                                    manufacturer = fmanufacturer,
                                    model = fmodel,
                                    fuel = fengineType,
                                    engineVol = fengineVol,
                                    year = fyear,
                                    checkDate = flastCheck,
                                    nextCheckDate = fnextCheck,
                                    kilometrage = fkilometrage)
            
            part_types = PartsType.objects.all()
            for part in part_types:
                Part.objects.create(carId = car, typeId = part, currentCondition = 0)
        
    else :
        error = "error in form"
    return redirect('main:main')

def get_cars_details(request):
    if 'user' in request.session:
        logged_user = User.objects.get(pk = request.session['user'])
        cars = Car.objects.filter(userId = logged_user)
        parts = Part.objects.filter(carId__in = cars)
        part_types = PartsType.objects.all()
        return {'cars' : cars, 'parts' : parts, 'part_types': part_types}

def update(request):
    form = UpdatePartForm(request.POST)
    if form.is_valid():
        part_id = form.cleaned_data.get('partId')
        form_value = form.cleaned_data.get('newValue')
        car_id = form.cleaned_data.get('carId')
        if form.cleaned_data.get('updateAll') == 1:
            car = Car.objects.get(pk = car_id)
            for part in Part.objects.filter(carId = car):
                if part.typeId.conditionMeasurment == 'km':
                    difference = form_value - car.kilometrage 
                    new_value = part.currentCondition + difference
                    updatePart(part.pk, new_value)
            car.kilometrage = form_value
            car.save()
            return main(request)
        updatePart(part_id, form_value)
    return redirect('main:main')


#private methods
def updatePart(part_id, new_value):
    part = Part.objects.get(pk = part_id)
    if part.currentCondition < new_value:
            part.currentCondition = new_value
    part.save()



    

main/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Check car</title>


    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
    
  </head>
  <body style="background: linear-gradient(189.63deg, #FFFFFF 45.05%, #E4EBF5 100%); "> <!---height: 100vh; -->

    

    <div style="position: fixed; width: 100vw; background: #FFFFFF; height: 110px; border-bottom: 2px solid #000000;  z-index: 5;">

      <h1 class="text-start" style="display:inline-block; padding-left: 1vw; font: 2vw cormorant; padding-top: 2vh;">Sākums</h1>
      <h1 class="text-center" style="display:inline-block; padding-left: 2vw; font: 2vw cormorant;">Jaunumi</h1>
      <h1 class="text-end" style="display:inline-block; padding-left: 2vw; font: 2vw cormorant;" >Patēriņā kalkulātors</h1>
      <a href="../login/login.html" style="display:inline-block; padding-left: 57vw; font: 2vw cormorant;">Iziet</a>

    </div>
    
    
    <img src="{% static 'img/logo.png' %}" alt="" class="text-center" style=" position: fixed; width:111px; height:100px;  z-index: 6; margin-left: 47.2vw; margin-right: auto;">
    <div id="newCarForm" class="row align-items-center justify-content-center border border-primary bg-white" style= "z-index: 3;position: fixed; margin : auto; top : 20%; left : 40% ;width: 400px; height : auto; padding-top : 15px;auto; padding-bottom : 15px;">
      <form action = "add_car" method = "post">
        {% csrf_token %}
        <div><label for="{{ new_car_form.manufacturer.id_for_label }}"><font face = "Cormorant SC">Mašīnas marka</font> </label></div>
        <div> {{new_car_form.manufacturer}} </div>
        <div><label for="{{ new_car_form.model.id_for_label }}"><font face = "Cormorant SC">Mašīnas modelis</font> </label></div>
        <div> {{new_car_form.model}} </div>
        <div><label for="{{ new_car_form.engineType.id_for_label }}"><font face = "Cormorant SC">Dzinējs</font></label></div>
        <div> {{new_car_form.engineType}} </div>
        <div><label for="{{ new_car_form.engineVol.id_for_label }}"><font face = "Cormorant SC">Dzinēja apjoms</font></label></div>
        <div> {{new_car_form.engineVol}} </div>
        <div><label for="{{ new_car_form.year.id_for_label }}"><font face = "Cormorant SC">Izgatavošanas gads</font></label></div>
        <div> {{new_car_form.year}} </div>
        <div><label for="{{ new_car_form.lastCheck.id_for_label }}"><font face = "Cormorant SC">Pedēja apskata datums</font> </label></div>
        <div> {{new_car_form.lastCheck}} </div>
        <div><label for="{{ new_car_form.nextCheck.id_for_label }}"><font face = "Cormorant SC">Nākama apskata datums</font> </label></label></div>
        <div> {{new_car_form.nextCheck}} </div>
        <div><label for="{{ new_car_form.kilometrage.id_for_label }}"><font face = "Cormorant SC">Nobraukums</font> </label></div>
        <div> {{new_car_form.kilometrage}} </div>
        <div style=" width: 25vw; height: 7vh; margin-top: 9vh; margin-left: -2px; border: 2px solid #000000; background-color: #F1F5F8; border-radius: 4px;">
          <button type = "submit" style="display:inline-block; margin-left: 1vw; width: 10vw; height: 4vh; background-color: #D0FF83; border-radius: 4px;"><font face = "Cormorant SC">Pievienot</font></button>
          <button type = "button" style="display:inline-block; margin-left: 1vw; margin-top: 0.7vh; width: 10vw; height: 4vh; background-color: #F1F5F8; border-radius: 4px;" onclick= "$('#newCarForm').hide()"> <font face = "Cormorant SC">Atpakaļ</font></button>
        </div>
      </form>
    </div>

    <div id="updatePartForm" class="row align-items-center justify-content-center border border-primary bg-white" style= "z-index: 3;position: fixed; margin : auto; top : 20%; left : 40% ;width: 32vw; height: 40vh">
      <form action = "update" method = "post">
        {% csrf_token %}
        <p class="text-center"><font face = "Cormorant SC" size="5px">Atjaunināt: {{part.typeId.typeName}}</font></p>
        <p class="text-center"><font face = "Cormorant SC" size="5px">Odometra rādijums uz doto brīdi:</font></p>
        <div><label for="{{ update_form.newValue.id_for_label }}"><font face = "Cormorant SC">km</font></label></div>
        <div> {{update_form.newValue}} </div>
        <div> {{update_form.partId}} </div>
        <div> {{update_form.carId}} </div>
        <div> {{update_form.updateAll}} </div>
        <div style=" width: 30vw; height: 7vh; margin-top: 9vh; margin-left: -2px; border: 2px solid #000000; background-color: #F1F5F8; border-radius: 4px;">
          <button type = "submit" style="display:inline-block; margin-left: 7vw; width: 10vw; height: 4vh; background-color: #D0FF83; border-radius: 4px;"> <font face = "Cormorant SC">Atjaunināt</font></label></button>
          <button type = "button" style="display:inline-block; margin-left: 1vw; margin-top: 0.7vh; width: 10vw; height: 4vh; background-color: #F1F5F8; border-radius: 4px;" onclick= "$('#updatePartForm').hide()"> <font face = "Cormorant SC">Atcelt</font></button>
        </div>
      </form>
    </div>
    <div style="width: 100%; height: 110px; z-index: 2; "></div>
    
    
    <div style="position: fixed; width: 50vw; height: 100vh;  margin-top: 0px;  border-right: 2px solid #000000;  " > 
      
      <div style="padding-top: 3.5vh; padding-bottom: 0.08vh; padding-left: 4vw; font: 20px cormorant;">
        <p style="display:inline-block; padding-left: 6vw;"><font face = "Cormorant SC">Mašīnas modelis</font></p>
      </div>
      
      
      <div class="row" style="padding-left: 4vw; padding-right: 4vw;">
        <div class = "col-4">  
          {% for car in cars %}
          <div class="row" style="padding-left: 4vw; padding-right: 4vw; padding-top: 1.5vh; width: 343px;">
            <button class="col" id="car" data-carId = {{ car.pk }} style="background-color: #FFFFFF; border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; width: 343px; height: 60px; text-align: center; " onclick="changeColor('car')">
              <font face = "Roboto">{{ car.manufacturer }}  {{ car.model }}</font>
            </button>
          </div>
          {% endfor %}
          <div class="row" style="padding-left: 4vw; padding-right: 4vw; padding-top: 3.5vh; width: 320px;">
            <button onclick= "$('#newCarForm').show()" style="background-color: #99C4FF; border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; width: 343px;; height: 60px; text-align: center; ">
              Pievienot + 
            </button>
          </div>
          </div>
          <div class = "col-4" > 
            {% for car in cars %}
              <div class = "car-data" data-carId = {{ car.pk }}>
                {% for key, value in car.main_info.items %}
                  {% if key != 'kilometrage' %}
                  <p style="display:inline-block; padding-left: 6vw;"><font face = "Cormorant SC">{{ key }}</font></p>
                  <div style="border: 2px solid #000000; margin-left: 140px; margin-right: 10px; border-radius: 6px; text-align: center; padding-top: 15px; padding-bottom: 15px; width: 200px;">
                    {{ value }}
                  </div>
                  {% endif %}
                {% endfor %}
              </div>
            {% endfor %}
        </div>
            
      </div>

      </div>
      
    </div>


  <div style="width: 50%; height: 130vh; margin-left: 50%; ">
      {% comment %} TODO hide this if another car is choosen {% endcomment %}
    {% for car in cars %}
    <div class="car-data" data-carId = {{ car.pk }}>
      <div style="padding-top: 4vh; padding-bottom: 1vh; padding-left: 4vw; font: 20px cormorant;">Pēdējais odometra rādījums: </div>

        <div class="row" style="padding-left: 4vw; padding-right: 4vw;">
          <div class="col" style="border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center; padding-bottom: 10px;">
            {{ car.kilometrage}} km
          </div>
          <div class="col" style="border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center; padding-bottom: 10px;">
            {{ car.checkDate}}
          </div>
          <button onclick = "showUpdateForm({{ car.kilometrage}}, null, {{ car.pk }} , true)" class="col" style="border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center;  background-color: #99C4FF;">
            Atjaunināt + 
          </button>
          <div class="col-5" style=" margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center; padding-top: 5px;">
          </div>
        </div>

        {% for part in car.get_car_parts %}
        <div style="padding-top: 4vh; padding-bottom: 1vh; padding-left: 4vw; font: 20px cormorant;"> <font face = "Cormorant SC">{{part.typeId.typeName}}</font></div>

          <div class="row" style="padding-left: 4vw; padding-right: 4vw;">
            <div class="col-2"><font face = "Cormorant SC">Pašreizējais :</font></div>
            <div class="col-2"><font face = "Cormorant SC">Maksimālais: </font></div>
          </div>
          <div class="row" style="padding-left: 4vw; padding-right: 4vw;">
            <div class="col" style="border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center; padding-bottom: 10px;">
              {{part.currentCondition}} {{part.typeId.conditionMeasurment}}
            </div>
            <div class="col" style="border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center; padding-bottom: 10px;">
              {{part.typeId.stockCondition}} {{part.typeId.conditionMeasurment}}
            </div>
            <button onclick = "showUpdateForm({{part.currentCondition}}, {{ part.pk }}, {{ car.pk }}, false)" class="col" style="border: 2px solid #000000; margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center;  background-color: #99C4FF;">
              Atjaunināt + 
            </button>
            <div class="col-5" style=" margin-left: 10px; margin-right: 10px; border-radius: 6px; height: 60px; text-align: center; padding-top: 5px;">
          </div>
        </div>
        {% endfor %}

      </div>
      {% endfor %}
    </div>
  </div>

    
      <script type="text/javascript">
        $(document).ready(function() {
          $( "#updatePartForm" ).hide();
          $( "#newCarForm" ).hide();
          $(".car-data").hide()

          $( document ).on("click", "#car" , function(){
            carId = $(this).attr("data-carId")
            $(".car-data").not(this).hide()
            $("div.car-data[ data-carId != '" + carId + "']").hide()
            $("div.car-data[data-carId = '" + carId + "']").show()

            $("#car").not(this).removeClass("active")
            $(this).addClass("active")
          })
        })


        function showUpdateForm(currentValue, partId, carId, updateAll){
          $( "#updatePartForm" ).show();
          $( "#id_newValue").val(currentValue)
          $( "#id_partId").val(partId)
          $( "#id_carId").val(carId)
          $( "#id_updateAll").val(updateAll ? 1 : 0)
        }
                
      </script>

<script type="text/javascript">

  var isPressed = false;
      function changeColor(btn) {
          var getBtn = document.getElementById(btn);
          if (isPressed == true) {
            getBtn.style.backgroundColor = "#FFFFFF"
            isPressed = false;        
          }
          else {
            getBtn.style.backgroundColor = "#EBF0F7"
            isPressed = true;
          }
      }
</script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

main/templates/manage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="css/style.css" />
    <title>depreciationControl.lv</title>
    <link rel="icon" type="image/x-icon" href="/img/favicon.png" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img
          src="img/logo.png"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">SĀKUMS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">JAUNUMI</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">PATĒRIŅA KALKULĀTORS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">IZIET</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="row vh-100 d-flex justify-content-center align-items-center">
        <div class="col-10 mx-auto">
          <h1 class="text-center">IZSTRĀDĀJUMĀ</h1>
          <div class="col-4 mx-auto text-center" style="padding-top: 5%">
            <a href="index.html">
              <img class="img-fluid" src="img/logo.png" alt=""
            /></a>
          </div>
        </div>
      </div>
    </div>

    <script src="js/jquery-3.6.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>